var SpellBinderData = {
    "name": "Add ed",
  "models": [ { "from":"present", "to":"presented", "rule":"adding ed" },
              { "from":"exaggerate", "to":"exaggerated","rule": "adding d" },
              { "from":"prefer", "to":"preferred", "rule":"doubling the last letter and adding ed"},
            ],
  "correct": [ "That's right. You wrote the word {answer} by {rule}.",
               "Good job! You created {answer} by {rule}." ],
    "wrongFirst": [ "That word is not correct. Look at the sample words at the top of the page to help you figure out how to add ed to this root word." ],
  "nextPrompt": [ "Try this one.",
                  "Now try this.",
                  "Here's another",
                ],
  "instructions": "<p>You are learning that sometimes words have spelling patterns that help you read them.  You just reviewed two spelling patterns that appear at the beginning of words, un and re.  Now, look at the spelling pattern, -ed, when it comes at the end of words.</p><p>You know how to read words that have an –ed or –d on the end.  In this lesson, you’re going to learn how to use that knowledge to help you figure out big words that have –ed or –d on the end.</p><p>These are some examples of big words that have –ed or -d added to them.  Take a look.</p><p>present &rarr; presented        exaggerate &rarr; exaggerated        prefer &rarr; preferred</p><p>Now, you will do an activity where you will complete sentences in a story by adding -ed  or –d to a root word.  The root word will be shown in parentheses.  Sometimes you have to change the spelling of a root word slightly before adding ed.  In other cases, you simply add –ed or –d.   Use the sample words at the top of the screen to help figure out what you need to do.</p>",
  "examples": "<p>Last week, I (inspect) ____________ the contents of my lunch box.</p><p>If you wrote inspected, you are correct. All you need to do is add ed to the word inspect without changing anything.</p><p>Let’s practice another one.</p><p>I (realize) __________ that I got my sister’s smelly tuna sandwich.</p><p>What did you do this time? The root word, realize, ends in an e, so all you need to do is add a d to make the word, realized.</p><p>Here’s one more before you try the rest on your own. </p><p>It (occur) __________ to me that I would remain hungry until dinner.</p><p>Occur is one of those words where you need to double the last consonant before adding ed. So, if you wrote occurred you are right!</p>",
  "sentences": [
      { "sentence": "I was (delight) __________ when I saw an ad for a contest.",
        "answer": "delighted", "model": 1 },
      { "sentence": "The students at our school (decide) __________ to produce on our own version of American Idol.",
        "answer": "decided", "model": 2 },
      { "sentence": "I (agree) __________ to try out but did not know what to sing.",
        "answer": "agreed", "model": 2 },
      { "sentence": "We were (allot) ___________ 2 minutes for each song.",
        "answer": "alloted", "model": 1 },
      { "sentence": "I (discuss) __________ the song I should sing with my friends.",
        "answer": "discussed", "model": 1 },
      { "sentence": "They (select) __________ a hard song.",
        "answer": "selected", "model": 1 },
      { "sentence": "I (practice) __________ all week.",
        "answer": "practiced", "model": 2 },
      { "sentence": "By Friday, I (despise) __________ that song.",
        "answer": "despised", "model": 2 },
      { "sentence": "I also (regret) ___________ the song choice and the hard work.",
        "answer": "regretted", "model": 3 },
      { "sentence": "At the same time, I knew I could not be (discourage) __________.",
        "answer": "discouraged", "model": 2 },
      { "sentence": "I was (determine) __________ to win!",
        "answer": "determined", "model": 2 },
      { "sentence": "Finally, the audition day (arrive) __________.",
        "answer": "arrived", "model": 1 },
      { "sentence": "All of the entrants (assemble) __________ in the auditorium.",
        "answer": "assembled", "model": 2 },
      { "sentence": "First, a judge (announce) __________ all of the participants.",
        "answer": "announced", "model": 2 },
      { "sentence": "Then, the first girl came onto the stage and (prepare) ___________ to sing.",
        "answer": "prepared", "model": 2 },
      { "sentence": "Someone (provide) __________ her with a microphone.",
        "answer": "provided", "model": 2 },
      { "sentence": "I was (overwhelm) __________ by it all.",
        "answer": "overwhelmed", "model": 1 },
      { "sentence": "I sat in my seat and (consider) __________ backing out.",
        "answer": "considered", "model": 1 },
      { "sentence": "I did not know my class was so (talent) __________.",
        "answer": "talented", "model": 1 },
      { "sentence": "For the first time it (occur) __________ to me that I might not make the cut.",
        "answer": "occurred", "model": 3 },
      { "sentence": "To stay calm, I (inhale) __________ a deep breath of air.",
        "answer": "inhaled", "model": 2 },
      { "sentence": "I was nervous as I (anticipate) __________ what it would feel like.",
        "answer": "anticipated", "model": 2 },
      { "sentence": "I also (repeat) __________ my song in my head.",
        "answer": "repeated", "model": 1 },
      { "sentence": "Suddenly, the judges (request) __________ that I take the stage.",
        "answer": "requested", "model": 1 },
      { "sentence": "Their voices (startle) _______ me.",
        "answer": "startled", "model": 2 },
      { "sentence": "I (scramble) __________ up on the stage and took another deep breath.",
        "answer": "scrambled", "model": 2 },
      { "sentence": "Luckily, I (settle) __________ down in a few seconds.",
        "answer": "settled", "model": 2 },
      { "sentence": "I (realize) __________ this was my big chance.",
        "answer": "realized", "model": 2 },
      { "sentence": " I also knew we were (permit) __________ one restart if we needed it.",
        "answer": "permitted", "model": 3 },
      { "sentence": "I sang my song and my voice (echo) _____ through the room. ",
        "answer": "echoed", "model": 1 },
      { "sentence": "It was better than I could have (imagine) __________.",
        "answer": "imagined", "model": 2 },
      { "sentence": "When I was done, the audience (applaud) __________ for a long time. ",
        "answer": "applauded", "model": 1 },
      { "sentence": "It (appear) __________ to go on forever.",
        "answer": "appeared", "model": 1 },
      { "sentence": "I (enjoy) __________ the attention.",
        "answer": "enjoyed", "model": 1 },
      { "sentence": "I also felt very (relieve) __________ to be done.",
        "answer": "relieved", "model": 2 },
      { "sentence": "At the end, the judges (confer) _______.",
        "answer": "conferred", "model": 3 },
      { "sentence": "They (linger) _______ over their decision.",
        "answer": "lingered", "model": 1 },
      { "sentence": "Forty people (perform) __________, but only 15 would be in the show.",
        "answer": "performed", "model": 1 },
      { "sentence": "I (listen) __________ until I finally heard my name.",
        "answer": "listened", "model": 1 },
      { "sentence": "I was thrilled and (exhaust) _____________ at the same time.",
        "answer": "exhausted", "model": 1 },
  ],
};
